Draft: cleanup
ironcore-dev/metal pull request #423
Opened 2024-01-22 09:39 UTC by aobort

**What this PR does / why we need it**:

- update Makefile
- update license
- update api-reference docs
- reorganize generated code
- harden linters

**Release note**:
```other user
chore works to cleanup and keep repo up to date
```

2024-02-05 15:58 UTC, Gchbg requested changes
Most of this is subjective and I suppose we could merge as is, but I personally feel the modification ot generate.sh was unnecessary. Please see below. Let's have a short out-of-band discussion and get this merged.

2024-02-05 15:58 UTC, Gchbg commented on controllers/machine/ipxe_controller.go
> +func (p *OnmetalImageParser) getOnmetalImage(url string) (*ironcoreimage.Image, error) {
Do we need to rename this stuff as well from onmetal?

2024-02-05 15:58 UTC, Gchbg commented on pkg/constants/switch.go
> +missing requirements: IP object of V4 address family to be assigned to loopback interface`
I think some (automated) reformatting went wrong here? It makes sense that these string would remain single-line.

2024-02-05 15:58 UTC, Gchbg commented on metal-provider/servers/grpc_server.go
> +		m := item
I'm not sure what is the reason for this change.

2024-02-05 15:58 UTC, Gchbg commented on hack/generate.sh
> +  --input-base ""
I guess this is very subjective but to me the modified version of the file is less clear (less "clean") than the one it replaces which was minimal and simple.

One key advantage of the old version is that it can be run standalone, i.e. just `hack/generate.sh`. I could be wrong but the new version seems to depend on a number of environment variables and is realistically only useable via the Makefile.

2024-02-06 14:31 UTC, aobort commented on controllers/machine/ipxe_controller.go
> +func (p *OnmetalImageParser) getOnmetalImage(url string) (*ironcoreimage.Image, error) {
I'd prefer to rename. So no confusion what the onmetal is

2024-02-06 15:44 UTC, aobort commented on metal-provider/servers/grpc_server.go
> +		m := item
Just curious, wdyt about such modification:
```go
	var machineApply *metalv1alpha4apply.MachineApplyConfiguration
	for _, m := range machineList.Items {
		if m.Status.Reservation.Status == "Available" && m.Status.Health == "Healthy" {
			machineApply = metalv1alpha4apply.Machine(m.Name, m.Namespace)
			break
		}
	}
	if machineApply == nil {
		err = status.Errorf(codes.ResourceExhausted, "no machine is available")
		log.Error(ctx, err)
		return nil, err
	}
	ctx = log.WithValues(ctx, "machine", &machineApply.Name)

	machineApply = machineApply.WithStatus(metalv1alpha4apply.MachineStatus().WithReservation(metalv1alpha4apply.Reservation().
		WithStatus("Reserved").WithClass(class)))
	machine := &metalv1alpha4.Machine{...}
```

2024-02-07 10:02 UTC, Gchbg submitted a review, later dismissed

2024-02-07 12:39 UTC, Gchbg approved these changes

2024-02-07 12:43 UTC, merged